/**
 * @module
 * @mergeModuleWith OAuth2
 */

import type {
  ClientAuthentication,
  APIClientConfiguration,
  JSONSerializable,
  JsonRecord,
  OAuth2Params,
  DiscrimUnion
} from '../types/index.ts';
import { APIClient } from '../http/index.ts';
import { buildURL, hasSameValues, validateURL } from '../utils/index.ts';


/** @internal */
export type OAuth2ClientConfigurations = DiscrimUnion<OAuth2Params & {
  baseURL: URL | string;
  discoveryURL?: URL | string;
}, 'issuer' | 'baseURL'>;

/**
 * Configuration options for {@link OAuth2Client}
 * @group OAuth2Client
 */
export type OAuth2ClientOptions = {
  authentication?: ClientAuthentication;
  allowHTTP?: boolean;
  syncClockWithAuthorizationServer?: boolean;
};

/**
 * Options to provide to {@link Configuration} at instantiation
 * @group OAuth2Client
 * @interface
 */
export type ConfigurationParams = OAuth2ClientConfigurations & OAuth2ClientOptions;

/**
 * Options to customize the behavior of a {@link OAuth2Client} instance
 * @group OAuth2Client
 * 
 * @see
 * {@link https://datatracker.ietf.org/doc/html/rfc8414 | RFC 8414: OAuth 2.0 Authorization Server Metadata}
 */
export class Configuration extends APIClient.Configuration implements APIClientConfiguration, JSONSerializable {
  /**
   * URL of the authorization server.
   */
  public readonly issuer: URL;
  /**
   * URL of the authorization server's Metadata document
   * @defaultValue
   * ```ts
   * this.issuer + '/.well-known/openid-configuration'
   * ```
   * 
   * @see
   * {@link https://datatracker.ietf.org/doc/html/rfc8414#section-3 | RFC 8414: Obtaining Authorization Server Metadata}
   */
  public readonly discoveryURL: URL;
  /**
   * Authorization server client identifier.
   * 
   * @remarks
   * The client identifier will be generated by the authorization server during client registration.
   * 
   * @see
   * {@link https://datatracker.ietf.org/doc/html/rfc6749#section-2.2 | RFC 6749: Client Identifier}
   */
  public readonly clientId: string;
  /**
   * Default `scope` value to be provided in authenication and token requests to the authorization server.
   * 
   * @see
   * * {@link https://developer.okta.com/docs/api/openapi/okta-oauth/oauth/orgas/authorize#orgas/authorize/t=request&in=query&path=scope | Okta Auth Server}
   * * {@link https://developer.okta.com/docs/api/oauth2 | Okta Scopes}
   * * {@link https://datatracker.ietf.org/doc/html/rfc6749#section-3.3 | RFC 6749: Access Token Scope}
   */
  public scopes: string;
  /**
   * Enum for possible authentication stratgies for authorization server requests. Defaults to `none` (aka public client)
   * 
   * @see
   * {@link https://datatracker.ietf.org/doc/html/rfc6749#section-2.3 | RFC 6749: Client Authentication}
   */
  public authentication: ClientAuthentication = 'none';
  /**
   * When `true`, issuer and other .well-known endpoints can be HTTP. Defaults to `false`
   */
  public allowHTTP: boolean = false;
  /**
   * When `true`, the `Date` header from HTTP requests made to the authorization server will be
   * used to calculate a clock skew between the authorization server and the system clock. This is
   * useful for situations when the client's system clock is set to something other than the "true time".
   *
   * Defaults to `true`.
   *
   * @remarks
   * By default, the `Date` header is not safelisted for CORS requests. The authorization Server will need
   * to include the `Date` header in the `allow-control-expose-headers` for this feature to work properly
   * when requests the authorization server and application are hosted on different origins.
   *
   * Reference: https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header
   */
  public syncClockWithAuthorizationServer: boolean = true;

  /**
   * @defaultValue
   * ```ts
   * {
   *   allowHTTP: false,
   *   syncClockWithAuthorizationServer: true,
   *   authentication: 'none',
   * 
   *   // inherited from APIClient
   *   dpop: false
   * }
   * ```
   */
  public static DefaultOptions: Required<OAuth2ClientOptions> & typeof APIClient.Configuration.DefaultOptions = {
    ...APIClient.Configuration.DefaultOptions,
    allowHTTP: false,
    syncClockWithAuthorizationServer: true,
    authentication: 'none'
  };

  constructor (params: ConfigurationParams) {
    const {
      baseURL,
      issuer,
      discoveryURL,
      clientId,
      scopes,
      authentication,
      dpop,
      allowHTTP,
      syncClockWithAuthorizationServer
    } = { ...Configuration.DefaultOptions, ...params };
    const url = issuer ?? baseURL;            // one of them must be defined via Discriminated Union
    if (!validateURL(url, allowHTTP)) {
      throw new TypeError('Invalid baseURL');
    }

    super({ dpop });
    this.issuer = new URL(url);
    this.discoveryURL = discoveryURL ? new URL(discoveryURL) : buildURL(this.baseURL, '/.well-known/openid-configuration');
    this.clientId = clientId;
    this.scopes = Array.isArray(scopes) ? scopes.join(' ') : scopes;

    // default values are set in `static DefaultOptions`
    this.authentication = authentication;
    this.allowHTTP = allowHTTP;
    this.syncClockWithAuthorizationServer = syncClockWithAuthorizationServer;
  }

  /**
   * Alias to {@link issuer} for backwards compatibility
   */
  get baseURL (): URL {
    return this.issuer;
  }

  /**
   * Determines whether a parameter collection matches the configuration of this client
   */
  matches (params: OAuth2Params): boolean {
    const { issuer, clientId, scopes } = params;

    // special case, don't return true when no actual params were provided to compare against
    if (Object.keys(params).length === 0) {
      return false;
    }

    let matches = true;
    if (issuer) {
      matches &&= new URL(issuer).href === this.baseURL.href;
    }

    if (clientId) {
      matches &&= clientId === this.clientId;
    }

    if (scopes) {
      const s = Array.isArray(scopes) ? scopes : scopes.split(' ');
      matches &&= hasSameValues(s, this.scopes.split(' '));
    }

    return matches;
  }

  /**
   * Returns configurations values of the client, omitting OAuth2 parameters
   * 
   * @see {@link Configuration.toJSON}
   */
  getOptions (): OAuth2ClientOptions {
    const { authentication, allowHTTP, syncClockWithAuthorizationServer } = this;
    return { authentication, allowHTTP, syncClockWithAuthorizationServer };
  }

  /**
   * Returns JSON representation of the client's configuration
   * 
   * @see {@link Configuration.getOptions}
   */
  toJSON (): JsonRecord {
    const { issuer, discoveryURL, clientId, scopes, authentication, allowHTTP, syncClockWithAuthorizationServer } = this;
    return {
      ...super.toJSON(),
      issuer: issuer.href,
      discoveryURL: discoveryURL.href,
      clientId,
      scopes,
      authentication,
      allowHTTP,
      syncClockWithAuthorizationServer
    };
  }
}
