/**
 * @module
 * @mergeModuleWith Flows
 */

import { SessionLogoutFlow as SessionLogoutFlowBase } from '@okta/oauth2-flows';


const defaultOptions: SessionLogoutFlow.PostRedirectOptions = {
  parentElement: document.body
};

/**
 * Browser-specific additions to {@link OAuth2Flows!SessionLogoutFlow | SessionLogoutFlow} to perform OIDC logout
 * 
 * @see
 * * {@link https://openid.net/specs/openid-connect-rpinitiated-1_0.html | OIDC RP-Initiated Logout}
 * 
 * @noInheritDoc
 */
export class SessionLogoutFlow extends SessionLogoutFlowBase {
  /**
   * Performs a full-page redirect to IDP OIDC `end_session_endpoint` via generated hidden `<form method="POST">`. Performing a `POST`
   * request (instead of `GET` which supported by most IDPs) avoids leaking the `id_token` within the URL query params.
   * 
   * @param logoutUrl - URL generated by {@link SessionLogoutFlow.start}
   * @param options.parentElement - Parent element to append the generated `<form>` element to. Defaults to `document.body`
   * @returns A {@link Promise} which never fulfills; therefore is blocking until the full-page redirect occurs.
   * 
   * @see
   * * {@link https://developer.okta.com/docs/api/openapi/okta-oauth/oauth/orgas/logoutwithpost | Okta Docs}
   */
  static PerformPostRedirect (logoutUrl: URL, options: Partial<SessionLogoutFlow.PostRedirectOptions> = {}) {
    const { parentElement } = { ...defaultOptions, ...options };

    // purposely a Promise which never resolves (the redirect should occur first)
    return new Promise(() => {
      // clone URL to avoid editing the passed instance
      logoutUrl = new URL(logoutUrl);

      // create html form
      const form = document.createElement('form');

      // appends values to form body
      for (const [key, value] of logoutUrl.searchParams.entries()) {
        const input = document.createElement('input');

        input.name = key;
        input.value = decodeURIComponent(value);
        input.type = 'hidden';

        form.appendChild(input);
      }

      // clears search params from URL since they are already appeneded to form
      logoutUrl.search = '';

      // append submit
      const submit = document.createElement('input');
      submit.type = 'submit';
      form.appendChild(submit);

      // sets properties of form element
      form.method = 'POST';
      form.style.display = 'none';
      form.action = logoutUrl.href;
      parentElement.appendChild(form);

      // submit the form (triggering redirect)
      submit.click();
    });
  }
}

/** {@inheritDoc SessionLogoutFlow} */
export namespace SessionLogoutFlow {
  export type PostRedirectOptions = {
    parentElement: HTMLElement;
  };
}
